// SPDX-License-Identifier: MIT
pragma solidity ^0.8.26;

/// @notice Mitigation mode selected by the Reactive risk engine.
enum MitigationMode {
    NONE,
    ADAPTIVE_FEE,
    THROTTLE,
    PAUSE,
    COMBINED
}

/// @notice Rolling telemetry emitted by SecurityHook after each observed swap.
struct PoolTelemetry {
    uint160 sqrtPriceX96;
    int24 tick;
    uint32 rollingVolatilityBps;
    uint32 priceDeviationBps;
    uint32 slippageBps;
    uint32 liquidityImbalanceBps;
    uint128 rollingVolume;
    uint64 observedAt;
    uint64 sequence;
    uint32 beforeSwapCount;
    uint32 afterSwapCount;
}

/// @notice Per-pool guardrails set by governance.
struct ProtectionConfig {
    uint24 baseFeePips;
    uint24 maxFeePips;
    uint16 maxThrottleBps;
    uint64 maxPauseSeconds;
}

/// @notice Mutable protection state enforced by the hook.
struct ProtectionState {
    uint24 currentFeePips;
    uint16 throttleBps;
    uint128 maxTradeSize;
    uint64 pauseUntil;
    uint16 lastRiskScoreBps;
    uint64 updatedAt;
    uint256 nonce;
}

/// @notice Callback payload generated by Reactive and consumed by SecurityExecutor.
struct MitigationPayload {
    uint24 dynamicFeePips;
    uint16 throttleBps;
    uint128 maxTradeSize;
    uint64 pauseSeconds;
    uint16 riskScoreBps;
    MitigationMode mode;
    bytes32 reason;
}
